// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package smgcontainer

import (
	"github.com/hetacode/go-bus"
	"github.com/hetacode/go-eh"
	"github.com/hetacode/mechelon/arch"
	"github.com/hetacode/mechelon/events"
	"github.com/hetacode/mechelon/services/services-mgmt/eventstore"
	"github.com/hetacode/mechelon/services/services-mgmt/types"
)

// Injectors from container.go:

func NewContainer() *Container {
	eventsMapper := events.NewEventsMapper()
	eventStore := initEventStoreProvider(eventsMapper)
	commandsConsumerBus := initCommandsConsumerBusProvider(eventsMapper)
	serviceStateRepository := initServiceStateRepositoryProvider(eventStore)
	container := &Container{
		EventStore:             eventStore,
		CommandsConsumerBus:    commandsConsumerBus,
		ServiceStateRepository: serviceStateRepository,
	}
	return container
}

// container.go:

type Container struct {
	EventStore             arch.EventStore
	CommandsConsumerBus    smgtypes.CommandsConsumerBus
	ServiceStateRepository *smgeventstore.ServiceStateRepository
}

func initServiceStateRepositoryProvider(es arch.EventStore) *smgeventstore.ServiceStateRepository {
	r := &smgeventstore.ServiceStateRepository{
		EventStore: es,
	}
	return r
}

func initCommandsConsumerBusProvider(em *goeh.EventsMapper) smgtypes.CommandsConsumerBus {
	kind := gobus.RabbitMQServiceBusOptionsFanOutKind
	bus := gobus.NewRabbitMQServiceBus(em, &gobus.RabbitMQServiceBusOptions{
		Kind:      &kind,
		Exchanage: "services-mgmt-ex",
		Queue:     "services-mgmt-commands-queue",
		Server:    "amqp://localhost:5673",
	})

	return bus
}

func initEventStoreProvider(em *goeh.EventsMapper) arch.EventStore {
	es := smgeventstore.NewServiceEventStore(em)
	return es
}
