// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package svvcontainer

// Injectors from container.go:

func NewContainer() *Container {
	container := &Container{}
	return container
}

// container.go:

// Container struct keep of all dependencies
type Container struct {
}
